RO Language Updates
Vanilla-OS/vanilla-installer pull request #198
Opened 2023-06-19 18:25 UTC by thednp

* Some instructions need to be more professional
* Other strings require a correct use of quotes
* Some explanations need to be more clear

2023-06-19 19:28 UTC, GabsEdits requested changes

2023-06-19 19:28 UTC, GabsEdits commented on po/ro.po
> +msgstr "Selectează aspectul preferat pentru tastatură"
```suggestion
msgstr "Selectează aspectul preferat pentru tastatura dvs."
```

2023-06-19 19:28 UTC, GabsEdits commented on po/ro.po
> +msgstr "Caută aspect tastatură"
```suggestion
msgstr "Caută un aspect pentru tastatură"
```

2023-06-20 08:21 UTC, GabsEdits approved these changes
Translations look good, Ready to merge

2023-07-12 17:58 UTC, kbdharun approved these changes

2023-07-12 17:58 UTC, merged