feat:[#335] Alert the user about missing minimum requirements
Vanilla-OS/vanilla-installer pull request #337
Opened 2024-01-07 03:56 UTC by muhdsalm

2024-01-07 09:44 UTC, Muqtxdir commented
hi @muhdsalm 

thanks for taking initiative on this one, it would be nicer if the host system requirements are shown against the minimum requirements as well
 So that they are aware which component doesn't meet minimum requirements

2024-01-10 20:24 UTC, MonsterObserver requested changes
Titles should use title case, the rest of the UI LGTM

2024-01-10 20:24 UTC, MonsterObserver commented on vanilla_installer/gtk/window-cpu.ui
> +                <property name="label">Not enough CPU cores</property>
```suggestion
                <property name="label">Not Enough CPU Cores</property>
```

2024-01-10 20:24 UTC, MonsterObserver commented on vanilla_installer/gtk/window-ram.ui
> +                <property name="label">Not enough RAM</property>
```suggestion
                <property name="label">Not Enough RAM</property>
```

2024-01-11 08:10 UTC, mirkobrombin approved these changes

2024-01-11 08:12 UTC, merged