feat[#314]: Tell user about minimum partition sizes
Vanilla-OS/vanilla-installer pull request #395
Opened 2024-07-25 16:15 UTC by muhdsalm

Closes #314

2024-07-25 17:35 UTC, taukakao requested changes

2024-07-25 17:35 UTC, taukakao commented on vanilla_installer/gtk/widget-partition.ui
> +        <property name="description" translatable="yes">The partition to mount under “/”. It will be automatically converted into an LVM thin pool during installation. Minimum space required in the p
This is not correct, the root needs around 21 GB, though I'm not sure how much exactly.

2024-07-25 17:35 UTC, taukakao commented on vanilla_installer/gtk/widget-partition.ui
> +        <property name="description" translatable="yes">The partition to mount under “/var”. This directory stores all user data like personal documents and system-wide configuration. Minimum space r
I don't think the installer checks for the size of /var.
5GB is too little tho, should be somewhere around 25-30 GB

2024-07-26 08:38 UTC, Muqtxdir reviewed
iwould suggest having min requirements specified in `recipe.json` and extracting the values from there. since if we go down the custom image route this would be different with other images

2024-07-31 06:01 UTC, mirkobrombin requested changes

2024-07-31 06:01 UTC, mirkobrombin commented on vanilla_installer/defaults/disk.py
> +        self.__recipe = RecipeLoader()
I suggest to use the instance from the window instead of making a new one

2024-08-01 06:51 UTC, muhdsalm commented
The code only required /var to have 5GB of space. Should I increase that?

2024-08-01 07:05 UTC, Muqtxdir approved these changes
thanks 👍

2024-08-01 07:05 UTC, Muqtxdir commented
> The code only required /var to have 5GB of space. Should I increase that?

now that it's being taken from recipe. we can change it later again in recipe if needed

2024-08-01 07:09 UTC, muhdsalm commented
> > The code only required /var to have 5GB of space. Should I increase that?
> 
> now that it's being taken from recipe. we can change it later again in recipe if needed

https://github.com/Vanilla-OS/vanilla-installer/blob/374a1242b1f70498b6bbbd80b0c635f6483d203d/vanilla_installer/defaults/disk.py#L198

2024-08-01 07:17 UTC, mirkobrombin reviewed
LGTM ( did not test )

2024-08-01 12:16 UTC, taukakao approved these changes

2024-08-01 12:16 UTC, taukakao commented
Thanks for the work. @muhdsalm

2024-08-01 12:16 UTC, merged