feat[#293]: Add "Do not format" toggle for /var partition in manual partitioning
Vanilla-OS/vanilla-installer pull request #407
Opened 2024-08-01 06:22 UTC by muhdsalm

Not entirely accurate: It's more of an option to format it as 'unformatted':

![image](https://github.com/user-attachments/assets/d7a60e9f-d2d6-4782-84c4-1f871d9b1788)

2024-08-01 09:42 UTC, taukakao requested changes
Apart from the partition label, you also need to give the filesystem for that partition the filesystem label "vos-var". Otherwise it won't be mounted by abroot. 

You probably also need to check if it has a supported filesystem on it.

An encrypted disk won't work, an ntfs drive won't work, an lvm won't work, at least not like this, etc.

2024-08-01 09:44 UTC, mirkobrombin commented
Note: do not merge in the next release of the installer

2024-11-27 02:15 UTC, taukakao approved these changes
LGTM

2024-11-27 02:16 UTC, taukakao commented
Thank you for contributing @muhdsalm and sorry for noticing this late that you requested a review.

2024-11-27 02:16 UTC, merged